services:
  backend:
    image: kalagaserge/commandkeeper-backend:latest
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
      DEFAULT_ADMIN_USERNAME: ${DEFAULT_ADMIN_USERNAME}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
    volumes:
      - backend_data:/data

  frontend:
    image: kalagaserge/commandkeeper-frontend:latest
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:2000"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_PROXY_TARGET: ${VITE_PROXY_TARGET}
    depends_on:
      - backend

volumes:
  backend_data:
